{application,ex_contract,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"This is Elixir library application that adds support for design by contract. For intro to DbC\n    methodology see https://en.wikipedia.org/wiki/Design_by_contract."},
              {modules,['Elixir.ExContract','Elixir.ExContract.Assert',
                        'Elixir.ExContract.BaseContractException',
                        'Elixir.ExContract.CheckException',
                        'Elixir.ExContract.CompileState',
                        'Elixir.ExContract.ConditionMsg',
                        'Elixir.ExContract.EnsuresException',
                        'Elixir.ExContract.FailException',
                        'Elixir.ExContract.RequiresException']},
              {registered,[]},
              {vsn,"0.1.2"}]}.
