{application,app,
             [{applications,[kernel,stdlib,elixir,logger,ecto_sql,postgrex]},
              {description,"app"},
              {modules,['Elixir.App.Application','Elixir.App.Repo',
                        'Elixir.App.Schemas.Animal','Elixir.App.Schemas.Note',
                        'Elixir.App.Schemas.Species']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.App.Application',[]}}]}.
